import type { BookingItem, ScheduledMatch } from "@/types";

export const MOCK_BOOKINGS: BookingItem[] = [
  {
    id: 1,
    bookingNo: "B202604240001",
    eventTitle: "LOL 챔피언스 코리아 2026 스프링 결승",
    roundLabel: "결승 1경기",
    startAt: "2026-04-24T18:30:00",
    venue: "LoL Park",
    seatLabels: ["VIP석 A5-12"],
    amount: 150_000,
    status: "CONFIRMED",
    bookedAt: "2026-04-20T15:30:00",
    customerName: "홍길동",
    customerEmail: "hong@example.com",
    paymentMethod: "카드",
  },
  {
    id: 2,
    bookingNo: "B202604250002",
    eventTitle: "발로란트 챔피언스 투어 코리아",
    roundLabel: "8강 1경기",
    startAt: "2026-04-25T17:00:00",
    venue: "코엑스 컨벤션홀",
    seatLabels: ["R석 B3-8", "R석 B3-9"],
    amount: 240_000,
    status: "CONFIRMED",
    bookedAt: "2026-04-21T10:15:00",
    customerName: "김철수",
    customerEmail: "kim@example.com",
    paymentMethod: "간편결제",
  },
  {
    id: 3,
    bookingNo: "B202604190003",
    eventTitle: "오버워치 리그 서울 다이너스티",
    roundLabel: "정규 시즌",
    startAt: "2026-03-15T19:00:00",
    venue: "e스타디움",
    seatLabels: ["S석 C2-15"],
    amount: 90_000,
    status: "WATCHED",
    bookedAt: "2026-04-19T14:20:00",
    customerName: "이영희",
    customerEmail: "lee@example.com",
    paymentMethod: "카드",
  },
  {
    id: 4,
    bookingNo: "B202604220004",
    eventTitle: "TFT 월드 챔피언십 코리아 예선",
    roundLabel: "예선 1라운드",
    startAt: "2026-05-01T16:00:00",
    venue: "LoL Park",
    seatLabels: ["A석 D1-5", "D1-6"],
    amount: 140_000,
    status: "PENDING_PAYMENT",
    bookedAt: "2026-04-22T09:45:00",
    customerName: "박민수",
    customerEmail: "park@example.com",
    paymentMethod: "계좌이체",
  },
];

// ====== 일정표 (SchedulePage 용) ======
// 백엔드 미연동 — 프론트 표시 전용 mock
const T1 = { code: "T1", name: "T1", color: "bg-red-500" };
const GEN = { code: "GEN", name: "Gen.G", color: "bg-zinc-900" };
const HLE = { code: "HLE", name: "Hanwha Life", color: "bg-orange-500" };
const KT = { code: "KT", name: "KT Rolster", color: "bg-red-700" };
const DRX = { code: "DRX", name: "DRX", color: "bg-blue-500" };
const DK = { code: "DK", name: "Dplus KIA", color: "bg-emerald-500" };
const NS = { code: "NS", name: "Nongshim", color: "bg-amber-500" };
const BRO = { code: "BRO", name: "OKBRO", color: "bg-pink-500" };
const KDF = { code: "KDF", name: "Kwangdong Freecs", color: "bg-indigo-700" };
const BFX = { code: "BFX", name: "BNK FearX", color: "bg-sky-500" };

const BLG = { code: "BLG", name: "Bilibili Gaming", color: "bg-rose-600" };
const WBG = { code: "WBG", name: "Weibo Gaming", color: "bg-blue-700" };
const JDG = { code: "JDG", name: "JD Gaming", color: "bg-red-800" };
const TES = { code: "TES", name: "Top Esports", color: "bg-yellow-500" };

const G2 = { code: "G2", name: "G2 Esports", color: "bg-zinc-700" };
const FNC = { code: "FNC", name: "Fnatic", color: "bg-orange-600" };

const VCT_DRX = { code: "DRX", name: "DRX VAL", color: "bg-blue-600" };
const VCT_GEN = { code: "GEN", name: "Gen.G VAL", color: "bg-zinc-900" };

const SEOUL = { code: "SEO", name: "서울 다이너스티", color: "bg-violet-600" };
const SFS = { code: "SFS", name: "샌프란시스코 쇼크", color: "bg-amber-600" };

export const MOCK_SCHEDULE: ScheduledMatch[] = [
  {
    id: 9001,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: T1,
    teamB: GEN,
    startAt: "2026-05-22T17:00:00",
    status: "LIVE",
    bestOf: 5,
    scoreA: 1,
    scoreB: 1,
    venue: "LoL Park",
  },
  {
    id: 9002,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: HLE,
    teamB: KT,
    startAt: "2026-05-22T20:00:00",
    status: "SCHEDULED",
    bestOf: 3,
    venue: "LoL Park",
  },
  {
    id: 9003,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: DK,
    teamB: DRX,
    startAt: "2026-05-23T17:00:00",
    status: "SCHEDULED",
    bestOf: 3,
    venue: "LoL Park",
  },
  {
    id: 9004,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: NS,
    teamB: BRO,
    startAt: "2026-05-23T20:00:00",
    status: "SCHEDULED",
    bestOf: 3,
    venue: "LoL Park",
  },
  {
    id: 9005,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: KDF,
    teamB: BFX,
    startAt: "2026-05-24T17:00:00",
    status: "SCHEDULED",
    bestOf: 3,
    venue: "LoL Park",
  },
  {
    id: 9006,
    leagueCode: "LPL",
    leagueName: "LPL 2026 Spring",
    game: "LOL",
    teamA: BLG,
    teamB: WBG,
    startAt: "2026-05-24T19:00:00",
    status: "SCHEDULED",
    bestOf: 3,
    venue: "Shanghai Arena",
  },
  {
    id: 9007,
    leagueCode: "LPL",
    leagueName: "LPL 2026 Spring",
    game: "LOL",
    teamA: JDG,
    teamB: TES,
    startAt: "2026-05-25T19:00:00",
    status: "SCHEDULED",
    bestOf: 3,
    venue: "Shanghai Arena",
  },
  {
    id: 9008,
    leagueCode: "MSI",
    leagueName: "MSI 2026 Play-in",
    game: "LOL",
    teamA: G2,
    teamB: FNC,
    startAt: "2026-05-28T22:00:00",
    status: "SCHEDULED",
    bestOf: 5,
    venue: "Berlin Studio",
  },
  {
    id: 9009,
    leagueCode: "VCT",
    leagueName: "VCT Pacific 2026",
    game: "VALORANT",
    teamA: VCT_DRX,
    teamB: VCT_GEN,
    startAt: "2026-05-29T18:00:00",
    status: "SCHEDULED",
    bestOf: 3,
    venue: "VCT Studio Seoul",
  },
  {
    id: 9010,
    leagueCode: "OWCS",
    leagueName: "OWCS 2026 Season Final",
    game: "OVERWATCH",
    teamA: SEOUL,
    teamB: SFS,
    startAt: "2026-05-30T19:00:00",
    status: "SCHEDULED",
    bestOf: 5,
    venue: "e스타디움",
  },
  {
    id: 9011,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: T1,
    teamB: KT,
    startAt: "2026-05-21T17:00:00",
    status: "FINISHED",
    bestOf: 3,
    scoreA: 2,
    scoreB: 1,
    venue: "LoL Park",
  },
  {
    id: 9012,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: GEN,
    teamB: HLE,
    startAt: "2026-05-21T20:00:00",
    status: "FINISHED",
    bestOf: 3,
    scoreA: 2,
    scoreB: 0,
    venue: "LoL Park",
  },
  {
    id: 9013,
    leagueCode: "LCK",
    leagueName: "LCK 2026 Spring",
    game: "LOL",
    teamA: DRX,
    teamB: NS,
    startAt: "2026-05-20T17:00:00",
    status: "FINISHED",
    bestOf: 3,
    scoreA: 0,
    scoreB: 2,
    venue: "LoL Park",
  },
  {
    id: 9014,
    leagueCode: "LPL",
    leagueName: "LPL 2026 Spring",
    game: "LOL",
    teamA: BLG,
    teamB: JDG,
    startAt: "2026-05-20T19:00:00",
    status: "FINISHED",
    bestOf: 3,
    scoreA: 2,
    scoreB: 1,
    venue: "Shanghai Arena",
  },
  {
    id: 9015,
    leagueCode: "VCT",
    leagueName: "VCT Pacific 2026",
    game: "VALORANT",
    teamA: VCT_DRX,
    teamB: VCT_GEN,
    startAt: "2026-05-19T18:00:00",
    status: "FINISHED",
    bestOf: 3,
    scoreA: 1,
    scoreB: 2,
    venue: "VCT Studio Seoul",
  },
];
